"""Publish the eval numbers as a machine-readable artifact.

The measured numbers are this project's headline claim, and they are quoted on
outward surfaces — a portfolio site, a résumé, a program README. Every one of
those quotes was, until now, a number **retyped by hand** from a text report.
That copy is where rot starts: on 2026-07-18 the public site was found carrying
category 88.9% / domain 94.4% when the shipped classifier measured 94.4% / 92.6%,
two prompt changes stale, because nothing compared the published text to the
source it came from.

This is the same fix as the SYS-004 contract artifact, applied to metrics: the
producer publishes one machine-readable file, and consumers assert against it
instead of retyping it. A number that is *generated* cannot drift from its run;
a number that is *typed* always eventually does.

Computed via ``gold_eval.metrics()`` — the same function ``eval_gate.py`` grades
against ``thresholds.toml`` — so the artifact, the CI gate and the printed report
cannot disagree with each other.

One input is not computed, though: ``evals/gold_predictions_v3.csv`` is a frozen
snapshot of a paid live run. Nothing used to tie it to the prompt behind it, so
editing ``classify.SYSTEM_PROMPT`` and bumping the version — without paying for a
gold re-run — would have this script stamp the NEW version onto the OLD prompt's
predictions, with ``--check`` green throughout. ``src/provenance.py`` closes that:
both modes now refuse to run when the snapshot's recorded fingerprint no longer
matches the prompt and models on disk.

Run locally:
    uv run python scripts/gen_metrics_artifact.py          # rewrite the artifact
    uv run python scripts/gen_metrics_artifact.py --check  # exit 1 if stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

import pandas as pd  # noqa: E402

import classify  # noqa: E402
import gold_eval  # noqa: E402
import provenance  # noqa: E402

ARTIFACT_PATH = REPO_ROOT / "evals" / "metrics.json"
GOLD_PATH = REPO_ROOT / "data" / "gold" / "gold.csv"
PREDS_PATH = REPO_ROOT / "evals" / "gold_predictions_v3.csv"
# Absolute, like its siblings above: this script is run from CI, from the repo root
# and from a worktree, and a guard that silently no-ops on a bad cwd is not a guard.
PROVENANCE_PATH = REPO_ROOT / provenance.PROVENANCE_PATH

# Rounded to one decimal because that is how the numbers are quoted everywhere —
# publishing more precision than any consumer uses invites a mismatch that is real
# in the file and invisible on the page.
_PCT = 1
_F1 = 3


def _pct(value: float) -> float:
    return round(value * 100, _PCT)


def build_artifact() -> dict:
    """Build the published metrics artifact from the committed v3 snapshot."""
    gold = gold_eval.load_gold(str(GOLD_PATH))
    preds = pd.read_csv(PREDS_PATH)
    merged = gold.rename(columns={"domain": "operational_domain"}).merge(preds, on="id")
    m = gold_eval.metrics(merged)

    gold_block: dict[str, object] = {
        "n": int(m["n"]),
        "source": "evals/gold_predictions_v3.csv",
        "category_accuracy": _pct(m["category_accuracy"]),
        "category_macro_f1": round(m["category_macro_f1"], _F1),
        "domain_accuracy": _pct(m["domain_accuracy"]),
        "domain_macro_f1": round(m["domain_macro_f1"], _F1),
        "judge_category_agreement": _pct(m["judge_category_agreement"]),
        "judge_domain_agreement": _pct(m["judge_domain_agreement"]),
    }
    # Region keys are conditional in metrics() so the frozen v2 two-axis snapshot
    # can still be graded; the v3 path always carries them.
    for key in ("region_accuracy", "region_macro_f1", "judge_region_agreement"):
        if key in m:
            gold_block[key] = (
                round(m[key], _F1) if key.endswith("macro_f1") else _pct(m[key])
            )

    return {
        "$comment": (
            "GENERATED by scripts/gen_metrics_artifact.py — do not hand-edit. "
            "Outward surfaces quoting these numbers should assert against this "
            "file rather than retyping them; see SYS-018 for the same pattern "
            "applied to wire contracts."
        ),
        "version": _project_version(),
        # Published from the RECORDED fingerprint, never recomputed from the live
        # SYSTEM_PROMPT. That direction is the whole point: the artifact must say
        # which prompt actually produced these numbers, so it stays truthful even
        # when the code has since moved on. main() is what refuses to publish in
        # that case -- keeping the two jobs separate means a divergence surfaces as
        # a pairing failure rather than as a silent re-stamp.
        "provenance": provenance.load(str(PROVENANCE_PATH))["recorded"],
        "gold": gold_block,
    }


def _project_version() -> str:
    """Read the shipped version from pyproject, so the artifact says what it measured."""
    text = (REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8")
    for line in text.splitlines():
        if line.strip().startswith("version"):
            return line.split("=", 1)[1].strip().strip('"').strip("'")
    return "unknown"


def main() -> int:
    """Write the metrics artifact, or verify it is current under ``--check``."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the committed artifact is current; do not write.",
    )
    args = parser.parse_args()

    # Gate BOTH modes, not just --check. The reported failure was the generator
    # stamping a new version onto old-prompt predictions, so refusing to *write* is
    # the half that actually closes it; --check only catches it after the fact.
    ok, message = provenance.check(
        provenance.load(str(PROVENANCE_PATH)),
        provenance.fingerprint(
            classify.SYSTEM_PROMPT,
            gold_eval.WORKHORSE_MODEL,
            gold_eval.JUDGE_MODEL,
        ),
    )
    if not ok:
        print(message, file=sys.stderr)
        return 1
    if message:
        print(message)

    rendered = json.dumps(build_artifact(), indent=2) + "\n"

    if args.check:
        if not ARTIFACT_PATH.exists():
            print(f"MISSING: {ARTIFACT_PATH}", file=sys.stderr)
            return 1
        if ARTIFACT_PATH.read_text(encoding="utf-8") != rendered:
            print(
                "STALE: evals/metrics.json does not match the committed "
                "predictions.\nRun: uv run python scripts/gen_metrics_artifact.py",
                file=sys.stderr,
            )
            return 1
        print("Metrics artifact is current.")
        return 0

    ARTIFACT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {ARTIFACT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
