"""Pin the frozen predictions snapshot to the prompt and models that produced it.

THE GAP THIS CLOSES. ``evals/gold_predictions_v3.csv`` is a frozen snapshot of a
paid live run, and ``scripts/gen_metrics_artifact.py`` turns it into the published
``evals/metrics.json`` — stamping on the version read from ``pyproject.toml``.
Until now nothing tied that snapshot to the *prompt* that produced it. Edit
``classify.SYSTEM_PROMPT``, bump the version, skip the (paid, manual) gold re-run,
and the generator would happily stamp the NEW version onto predictions produced by
the OLD prompt. ``--check`` stayed green the whole way, because it only ever
compared the artifact against the snapshot, the gold set and the version string.

That is the same retyped-number drift the metrics artifact was built on 2026-07-18
to prevent — arriving through the generator instead of through a human, which makes
it worse: a generated number carries the authority of having been computed.

WHY A SIDECAR FILE. The recorded fingerprint has to live somewhere the *generator
does not author*. Putting both the live and the recorded value in ``metrics.json``
would be no guard at all: ``build_artifact()`` would recompute both from the same
live ``SYSTEM_PROMPT`` on every regeneration, so they could never disagree. Stamping
it into the predictions CSV was the other candidate and is rejected on blast radius —
twelve call sites read those prediction files with a plain ``pd.read_csv``, and a
``#`` metadata line does not raise there, it silently collapses the frame to a single
garbage column. Silent wrong data is a worse failure than the one being fixed.

So the record is written by the *producer* (``src/gold_eval.py``, at run time) into a
sidecar named after the data it describes. The generator can read it and cannot
launder it.

TWO READERS, ONE PAIRING. ``src/eval_gate.py`` grades that same frozen snapshot against
``evals/thresholds.toml`` on every push and PR, so the identical failure was reachable one
file over: edit the prompt, skip the paid re-run, and the offline gate reports the measured
floors as met for a classifier that is not the one shipped. Both readers therefore call
``check()`` before doing their work — the generator before publishing, the gate before
grading. The remedy is shared; only ``consequence`` differs.

WHAT IS FINGERPRINTED. The prompt and both model ids. A model swap invalidates a
snapshot exactly as thoroughly as a prompt edit — commit 6efbddf migrated the
workhorse to Sonnet 5 — so pinning only the prompt would leave an equivalent hole
open next door.

Deliberately hashlib-only: ADR-004 bans frameworks in the metric path and this repo
keeps its dependencies minimal.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

# Sidecar for the v3 gold snapshot. Named after the file it describes so the pairing
# is obvious in a directory listing and in a PR diff.
PROVENANCE_PATH = "evals/gold_predictions_v3.provenance.json"

_COMMENT = (
    "GENERATED by src/gold_eval.py at run time — do not hand-edit, except to add a "
    "'waiver' block. This records WHICH prompt and models produced the sibling "
    "predictions snapshot; scripts/gen_metrics_artifact.py refuses to publish "
    "metrics when the recorded fingerprint no longer matches the code on disk."
)


def fingerprint(prompt: str, workhorse_model: str, judge_model: str) -> dict[str, str]:
    """Identify a run by the prompt text and the two model ids behind it.

    Pure by design — it takes the values rather than importing ``classify`` and
    ``gold_eval`` to read them. That keeps this module free of the import cycle
    (``gold_eval`` imports this one) and makes it testable without a live key.

    Args:
        prompt: The classifier system prompt used for the run.
        workhorse_model: Model id scored against the human labels.
        judge_model: Model id scored for judge-vs-human agreement.

    Returns:
        Mapping with ``prompt_sha256`` (full 64-char hex digest of the UTF-8
        prompt bytes) plus both model ids.
    """
    return {
        "prompt_sha256": hashlib.sha256(prompt.encode("utf-8")).hexdigest(),
        "workhorse_model": workhorse_model,
        "judge_model": judge_model,
    }


def render(recorded: dict[str, str], predictions_path: str) -> str:
    """Serialize a provenance record exactly as it is written to disk.

    Shared with the writer so a test can assert the on-disk bytes without
    reimplementing the formatting (the same reason ``gen_metrics_artifact``
    renders through one function).

    Args:
        recorded: A ``fingerprint()`` mapping.
        predictions_path: Repo-relative path of the snapshot it describes.

    Returns:
        The JSON text, newline-terminated.
    """
    payload = {
        "$comment": _COMMENT,
        "predictions": predictions_path,
        "recorded": dict(recorded),
    }
    return json.dumps(payload, indent=2) + "\n"


def write(
    recorded: dict[str, str],
    predictions_path: str,
    path: str = PROVENANCE_PATH,
) -> None:
    """Write the provenance sidecar for a run that just produced predictions.

    Only ever called when API calls were actually made. Re-stamping this file on a
    report-only rerun would assert that today's prompt produced yesterday's rows,
    which is the precise laundering this module exists to prevent.

    Args:
        recorded: A ``fingerprint()`` mapping for the run.
        predictions_path: Repo-relative path of the snapshot it describes.
        path: Destination sidecar path. Defaults to ``PROVENANCE_PATH``.
    """
    Path(path).write_text(render(recorded, predictions_path), encoding="utf-8")


def load(path: str = PROVENANCE_PATH) -> dict:
    """Read the provenance sidecar.

    Args:
        path: Sidecar path. Defaults to ``PROVENANCE_PATH``.

    Returns:
        The parsed record.

    Raises:
        FileNotFoundError: If the sidecar is absent, with the remedy in the message.
            It is deliberately not defaulted-away: a missing record means the
            pairing is unknown, and an unknown pairing must not read as a passing one.
    """
    file = Path(path)
    if not file.exists():
        raise FileNotFoundError(
            f"{path} is missing, so nothing pins the predictions snapshot to the "
            f"prompt that produced it. It is written by a real gold run "
            f"(uv run --env-file .env python src/gold_eval.py). Do not hand-create "
            f"it to silence this — a fabricated fingerprint is worse than none."
        )
    return json.loads(file.read_text(encoding="utf-8"))


def divergences(recorded: dict[str, str], live: dict[str, str]) -> list[str]:
    """Describe every field on which a recorded run disagrees with the code on disk.

    Args:
        recorded: The fingerprint stored beside the snapshot.
        live: A ``fingerprint()`` of the current ``classify``/``gold_eval`` values.

    Returns:
        One human-readable line per differing field; empty when they agree.
    """
    out = []
    for key in ("prompt_sha256", "workhorse_model", "judge_model"):
        was, now = recorded.get(key), live.get(key)
        if was != now:
            out.append(f"  {key}:\n    snapshot: {was}\n    code now: {now}")
    return out


# What goes wrong if a stale snapshot is used anyway. Caller-supplied because the two
# guards fail for different reasons: the generator would publish numbers under a version
# whose prompt never produced them, while the CI gate would report the measured floors as
# met for a classifier that is not the one on disk. The remedy below is shared -- it is
# the same re-run either way -- but naming the wrong consequence sends the reader to the
# wrong file.
PUBLISH_CONSEQUENCE = (
    "Publishing now would stamp the current version onto predictions the "
    "current classifier never made."
)


def check(
    record: dict,
    live: dict[str, str],
    consequence: str = PUBLISH_CONSEQUENCE,
) -> tuple[bool, str]:
    """Decide whether the snapshot may still be used against the current code.

    Passes when the recorded fingerprint matches ``live``, or when a waiver in the
    record explicitly accepts exactly this ``live`` fingerprint and says why.

    The waiver exists because the alternative is worse. Without one, any edit to the
    prompt — a whitespace fix, a rubric reword — hard-blocks CI until someone pays
    for a full gold re-run, and a guard that expensive to satisfy gets deleted the
    first time it is inconvenient. The waiver does not weaken the guard, it changes
    the failure from *silent* to *on the record*: it must name the exact new
    fingerprint (so it cannot be a blanket skip), it must carry a reason, and it
    auto-expires the moment anything changes again.

    Args:
        record: A loaded provenance record.
        live: A ``fingerprint()`` of the current values.
        consequence: One sentence naming what using the stale snapshot would cause,
            interpolated into the failure message ahead of the shared remedy.
            Defaults to the publish wording (``PUBLISH_CONSEQUENCE``).

    Returns:
        ``(ok, message)``. The message explains the failure, or names the waiver in
        force, or is empty when the fingerprints simply match.
    """
    recorded = record.get("recorded", {})
    if not divergences(recorded, live):
        return True, ""

    waiver = record.get("waiver") or {}
    accepts, reason = waiver.get("accepts") or {}, (waiver.get("reason") or "").strip()
    if accepts and not divergences(accepts, live) and reason:
        return True, f"WAIVED: snapshot predates the current prompt/models — {reason}"

    detail = "\n".join(divergences(recorded, live))
    return False, (
        "STALE SNAPSHOT: evals/gold_predictions_v3.csv was produced by a different "
        "prompt or model than the code on disk.\n\n"
        f"{detail}\n\n"
        f"{consequence} Either:\n"
        "  1. Re-run the gold eval so the numbers describe the shipped classifier:\n"
        "       uv run --env-file .env python src/gold_eval.py\n"
        "       uv run python scripts/gen_metrics_artifact.py\n"
        "  2. Or explain why the snapshot still stands, by adding a waiver to\n"
        f"     {PROVENANCE_PATH}:\n"
        '       "waiver": {"accepts": {<the "code now" values above>},\n'
        '                  "reason": "<why these numbers still describe the '
        'shipped classifier>"}\n'
    )
