"""A/B the `global`-boundary prompt clause against the v3.2.0 n=300 ruler.

VERDICT, AND WHAT THIS MODULE IS NOW. The clause was written, pre-registered, run, and
**reverted** -- see `decisions/archive/023-global-boundary-clause-verdict.md`. The region lift
was real (88.5% -> 92.2%, 12 of 17 named pulls fixed) but landed at **McNemar
p=0.0522** against a decision rule pre-registered at p<0.05, and that rule says a
marginal result reverts. So `classify.SYSTEM_PROMPT` on `main` does NOT carry the
clause, and this module is the reproducible record of the measurement plus the ruler a
higher-power re-run would use. `evals/region_clause_ab.txt` and the two candidate arms
are frozen records; ``--report`` will refuse to re-derive them on `main`, because
:func:`assert_candidate_matches_the_live_prompt` correctly observes that the live prompt
is no longer the one that produced them. That refusal is the guard working, not a bug.

WHAT THIS MEASURES. `evals/scale_predictions_v3.csv` (ADR-022) recorded, for each of
300 DVIDS snippets, a workhorse label and an Opus-judge label. 17 of the 70 answer-key
``global`` rows were pulled to a specific region -- 16 to ``americas`` -- which is 49%
of every region disagreement in that run. The prompt clause this harness was built for
targets exactly that pull. This harness measures whether it works, and what it costs on
the other two axes.

THE CHEAP TRICK, AND WHY IT IS SOUND. A candidate arm normally costs 600 calls: 300
workhorse + 300 judge. It costs **300 here**, because the judge labels are reused from
the committed baseline snapshot rather than re-run. That is legitimate for one specific,
verifiable reason: ``gold_eval.run_predictions`` classifies each row with the workhorse
and the judge **independently, from the snippet text alone** -- neither model is shown
the other's answer. So a judge label is a function of (snippet, judge model, judge
prompt) and carries no dependence whatsoever on the workhorse's prediction. Changing the
workhorse's prompt cannot change what the judge would have said about that row.

Reusing the stored labels is therefore not a shortcut around a measurement, it is the
*correct* design: an answer key that moved between arms would confound the comparison
outright. The judge stays frozen at the values ADR-022 published, so the two arms are
graded by one identical ruler and every row difference is attributable to the prompt.

Note the direction of that argument carefully. ``classify()`` defaults BOTH models to
``classify.SYSTEM_PROMPT``, so a *fresh* judge pass under a candidate prompt would grade
under that prompt and produce a different, prompt-confounded answer key. Not re-running
the judge is what keeps the key fixed. :func:`assert_answer_key_is_complete` enforces
that the key really is the committed baseline's, and :func:`assert_arms_differ` enforces
that the two arms differ by the prompt and nothing else.

WHAT IS NEVER TOUCHED. Every artifact this writes is new and `region_clause`-named. The
v3.2.0 records (``evals/scale_predictions_v3.csv`` and its sidecar, ``scale_eval_v3.txt``,
``scale_confusion_v3_region.csv``) are a shipped, frozen measurement and are opened
read-only. Nothing here writes to ``evals/thresholds.toml``, ``evals/metrics.json``, or
any gold artifact.

A NEW MODULE, NOT A MODE ON ``scale_region_eval``. Same reasoning that spec used for not
extending ``scale_eval``: that module owns frozen outputs, and giving it a second write
path is how a frozen record eventually gets regenerated by someone reaching for the
nearest flag. This module imports the shared prediction pieces and owns only new paths.

Run -- the live pass is owner-driven (300 workhorse calls); the report is free:

    uv run --env-file .env python src/region_clause_ab.py --run
    uv run --env-file .env python src/region_clause_ab.py --run --batch
    uv run python src/region_clause_ab.py --report

``--run`` is resume-safe: rows append as they land and a re-run skips ids already
present. A resume across a prompt or model change is refused rather than blended.
``--report`` makes no API call, needs no key, and is repeatable.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import time

import anthropic
import pandas as pd

import paired_compare
import provenance
import scale_eval
from classify import (
    SYSTEM_PROMPT,
    BatchItemError,
    InvalidLabelError,
    build_batch_request,
    make_client,
    parse_batch_result,
)
from gold_eval import (
    JUDGE_MODEL,
    SLEEP_BETWEEN_CALLS,
    WORKHORSE_MODEL,
    classify_retry,
)
from run_isolation import atomic_write_text

SCALE_SET_PATH = scale_eval.SCALE_SET_PATH

# The frozen v3.2.0 baseline arm: the committed workhorse predictions AND the judge
# labels this comparison grades both arms against. Read-only, always.
BASELINE_PREDS_PATH = "evals/scale_predictions_v3.csv"
BASELINE_PROVENANCE_PATH = "evals/scale_predictions_v3.provenance.json"

# Everything this module writes. All new paths; none of them shadow a frozen record.
CANDIDATE_PREDS_PATH = "evals/region_clause_candidate.csv"
CANDIDATE_PROVENANCE_PATH = "evals/region_clause_candidate.provenance.json"
REPORT_PATH = "evals/region_clause_ab.txt"

GLOBAL = "global"
PRIMARY_AXIS = "region"

# (axis, judge/answer-key column). Region is the target; the other two are guardrails.
# ADR-020 is why they are not optional: the L4 critic fixed its named region cluster and
# did statistically significant damage to the domain axis (p=0.016) at the same time. A
# region-only report would have called that experiment a success.
AXES = [
    ("region", "judge_region"),
    ("category", "judge_category"),
    ("operational_domain", "judge_operational_domain"),
]

CANDIDATE_COLUMNS = ["id", "pred_category", "pred_operational_domain", "pred_region"]


# ---------------------------------------------------------------------------
# Guards. These run before any number is computed, because each one describes a
# way this comparison could produce a clean-looking result that means nothing.
# ---------------------------------------------------------------------------


def assert_resume_is_honest(done_ids: set, live: dict[str, str]) -> None:
    """Refuse to append today's classifier's rows onto yesterday's.

    Same rule ``gold_eval`` and ``scale_region_eval`` apply to their own snapshots: a
    file half-written under one prompt and half under another is a blend no single
    fingerprint can describe. A fresh run has nothing to blend and is always allowed.

    Args:
        done_ids: Ids already present in the candidate predictions CSV.
        live: A ``provenance.fingerprint`` of the current prompt and models.

    Raises:
        ValueError: If existing rows were produced by a different prompt or model.
    """
    if not done_ids or not os.path.exists(CANDIDATE_PROVENANCE_PATH):
        return
    recorded = provenance.load(CANDIDATE_PROVENANCE_PATH)["recorded"]
    drift = provenance.divergences(recorded, live)
    if not drift:
        return
    raise ValueError(
        f"Cannot resume {CANDIDATE_PREDS_PATH}: the {len(done_ids)} existing rows were "
        "produced by a different prompt or model.\n"
        + "\n".join(drift)
        + f"\n\nResuming would mix two classifiers in one arm. Delete "
        f"{CANDIDATE_PREDS_PATH} and {CANDIDATE_PROVENANCE_PATH} and re-run."
    )


def assert_arms_differ(baseline: dict[str, str], candidate: dict[str, str]) -> None:
    """Refuse to report an A/B whose two arms are not a clean prompt contrast.

    Two failure modes, both of which produce a perfectly well-formed report:

    - **Same prompt on both sides.** The candidate run was made before the clause
      landed, or against a stale checkout. The "lift" is then pure run-to-run sampling
      noise being read as an effect.
    - **A model changed too.** Then the experiment is a prompt *and* model A/B and no
      row-level difference can be attributed to the clause.

    Args:
        baseline: The ``recorded`` block of the baseline snapshot's sidecar.
        candidate: The ``recorded`` block of the candidate run's sidecar.

    Raises:
        ValueError: If the prompts match, or either model id differs.
    """
    if baseline.get("prompt_sha256") == candidate.get("prompt_sha256"):
        raise ValueError(
            "Both arms were produced by the SAME prompt "
            f"({candidate.get('prompt_sha256')}). There is no clause to measure -- any "
            f"difference would be sampling noise. Was {CANDIDATE_PREDS_PATH} produced "
            "before the clause was added, or on a checkout without it?"
        )
    for key in ("workhorse_model", "judge_model"):
        if baseline.get(key) != candidate.get(key):
            raise ValueError(
                f"The two arms disagree on {key}: baseline {baseline.get(key)!r} vs "
                f"candidate {candidate.get(key)!r}. This is a prompt A/B; a model swap "
                "makes every row-level difference unattributable. Re-run the candidate "
                "arm on the baseline's models."
            )


def judge_digest(baseline: pd.DataFrame) -> str:
    """A content fingerprint of the answer key itself, printed in every report.

    Column presence and non-blankness say nothing about *which* labels are in the file.
    This digests the (id, judge label) pairs for all three axes in id order, so two
    reports produced against the same answer key carry the same digest and one produced
    against an edited key does not. It is an auditable value, not a secret: a reviewer
    can recompute it from the committed CSV.

    Args:
        baseline: The loaded baseline predictions frame.

    Returns:
        A 16-hex-character digest.
    """
    ordered = baseline.sort_values("id")
    payload = "\n".join(
        "|".join([str(row["id"])] + [str(row[col]) for _axis, col in AXES])
        for _, row in ordered.iterrows()
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


def assert_answer_key_is_complete(baseline: pd.DataFrame, scale: pd.DataFrame) -> None:
    """Refuse an answer key that is not the whole committed scale set.

    The earlier version of this guard checked only that the judge columns existed and
    held no empty strings -- which a hand-assembled 50-row file passes, and which the
    production path could not even fail, because ``pd.read_csv`` turns a blank cell into
    ``NaN`` rather than ``""``. Both holes are closed here: the key must cover exactly
    the ids in ``data/scale/scale_set.csv``, with no duplicates and no missing labels,
    and callers load with ``dtype=str, keep_default_na=False`` so a blank really is
    ``""``.

    Args:
        baseline: The loaded baseline predictions frame.
        scale: The scale set the run is defined over.

    Raises:
        ValueError: If a judge column is missing, the id sets differ, ids repeat, or any
            judge label is blank.
    """
    for _axis, judge_column in AXES:
        if judge_column not in baseline.columns:
            raise ValueError(
                f"{BASELINE_PREDS_PATH} has no {judge_column!r} column, so it cannot "
                "supply the frozen answer key this comparison grades against."
            )

    ids = [str(row_id) for row_id in baseline["id"]]
    duplicated = sorted({row_id for row_id in ids if ids.count(row_id) > 1})
    if duplicated:
        raise ValueError(
            f"{BASELINE_PREDS_PATH} repeats {len(duplicated)} id(s) "
            f"({duplicated[:5]}). Pairing would drop every one of them."
        )

    expected = {str(row_id) for row_id in scale["id"]}
    missing, extra = sorted(expected - set(ids)), sorted(set(ids) - expected)
    if missing or extra:
        raise ValueError(
            f"{BASELINE_PREDS_PATH} is not the committed scale set: "
            f"{len(missing)} id(s) missing (e.g. {missing[:5]}), "
            f"{len(extra)} unexpected (e.g. {extra[:5]}). An answer key covering a "
            "subset silently shrinks the comparison instead of failing it."
        )

    for _axis, judge_column in AXES:
        blank = int((baseline[judge_column].astype(str).str.strip() == "").sum())
        if blank:
            raise ValueError(
                f"{BASELINE_PREDS_PATH} has {blank} blank {judge_column!r} cells. An "
                "answer key with holes silently shrinks the comparison."
            )


def assert_candidate_is_complete(
    baseline: pd.DataFrame, candidate: pd.DataFrame
) -> None:
    """Refuse a partial candidate arm.

    The batch path deliberately skips a row it cannot parse and leaves it todo, so an
    interrupted or partially-failed run produces a perfectly well-formed report over
    250 rows. Decision rule #4 ("harness health clean") was printed but not enforced;
    this enforces it.

    Args:
        baseline: The loaded baseline predictions frame.
        candidate: The loaded candidate predictions frame.

    Raises:
        ValueError: If the two arms do not cover exactly the same ids.
    """
    base_ids = {str(row_id) for row_id in baseline["id"]}
    cand_ids = [str(row_id) for row_id in candidate["id"]]
    duplicated = sorted({row_id for row_id in cand_ids if cand_ids.count(row_id) > 1})
    if duplicated:
        raise ValueError(
            f"{CANDIDATE_PREDS_PATH} repeats {len(duplicated)} id(s) "
            f"({duplicated[:5]}) -- an appended re-run over rows already present?"
        )
    missing = sorted(base_ids - set(cand_ids))
    extra = sorted(set(cand_ids) - base_ids)
    if missing or extra:
        raise ValueError(
            f"The candidate arm is not complete: {len(missing)} id(s) missing "
            f"(e.g. {missing[:5]}), {len(extra)} unexpected (e.g. {extra[:5]}). "
            f"Re-run `--run` to finish it -- it is resume-safe and skips rows already "
            "present. Reporting a partial arm would compute a clean lift over a "
            "harness that dropped its hardest rows."
        )


def assert_candidate_matches_the_live_prompt(
    candidate_recorded: dict[str, str],
) -> None:
    """Refuse to report a candidate arm the prompt on disk did not produce.

    ``assert_arms_differ`` only proves the two arms differ from each other -- a
    candidate CSV produced by some *third* prompt passes it. This pins the candidate to
    the working tree, so the report describes the clause actually in ``classify.py``.

    Args:
        candidate_recorded: The ``recorded`` block of the candidate run's sidecar.

    Raises:
        ValueError: If the candidate's prompt fingerprint is not the live one.
    """
    live = provenance.fingerprint(SYSTEM_PROMPT, WORKHORSE_MODEL, JUDGE_MODEL)
    drift = provenance.divergences(candidate_recorded, live)
    if drift:
        raise ValueError(
            "The candidate arm was not produced by the prompt/models on disk:\n"
            + "\n".join(drift)
            + "\n\nThe report would describe a classifier this checkout does not "
            f"contain. Delete {CANDIDATE_PREDS_PATH} and "
            f"{CANDIDATE_PROVENANCE_PATH} and re-run."
        )


# ---------------------------------------------------------------------------
# The candidate arm: workhorse only.
# ---------------------------------------------------------------------------


def run_workhorse(
    client: anthropic.Anthropic,
    df: pd.DataFrame,
    done_ids: set,
    preds_path: str = CANDIDATE_PREDS_PATH,
    system_prompt: str = SYSTEM_PROMPT,
) -> None:
    """Classify every not-yet-done snippet with the workhorse alone, appending as we go.

    Deliberately a workhorse-only twin of ``gold_eval.run_predictions`` rather than a
    new parameter on it: that function is the frozen call path both published snapshots
    were produced through, and the safest edit to it is none. The per-call path IS
    shared -- this calls ``gold_eval.classify_retry`` unchanged, so retry policy, model
    id, and ``classify()``'s wire shape are identical to the baseline arm's. The only
    difference between the arms is ``classify.SYSTEM_PROMPT``, which is the experiment.

    Args:
        client: Authenticated Anthropic client.
        df: Frame with at least columns ``id`` and ``text``.
        done_ids: Ids that already have predictions and can be skipped.
        preds_path: CSV the workhorse predictions are appended to.
        system_prompt: Prompt to classify under. Defaults to the live
            ``SYSTEM_PROMPT`` -- which is how the ADR-023 arm was produced, on a
            branch that carried the clause. The higher-power re-run passes the
            clause-applied prompt here instead, so ``main`` never has to hold a
            prompt it does not ship (see ``src/region_clause_rerun.py``).
    """
    todo = df[~df["id"].isin(done_ids)].reset_index(drop=True)
    write_header = not os.path.exists(preds_path)
    for i, (_, row) in enumerate(todo.iterrows()):
        print(f"[{i + 1:3d}/{len(todo)}] {row['id']}", flush=True)
        base = classify_retry(
            client, row["text"], WORKHORSE_MODEL, system_prompt=system_prompt
        )
        result = {
            "id": row["id"],
            "pred_category": base["category"],
            "pred_operational_domain": base["operational_domain"],
            "pred_region": base["region"],
        }
        pd.DataFrame([result])[CANDIDATE_COLUMNS].to_csv(
            preds_path, mode="a", header=write_header, index=False
        )
        write_header = False
        time.sleep(SLEEP_BETWEEN_CALLS)


def run_workhorse_batch(
    client: anthropic.Anthropic,
    df: pd.DataFrame,
    done_ids: set,
    poll_interval: float = 30.0,
    preds_path: str = CANDIDATE_PREDS_PATH,
    system_prompt: str = SYSTEM_PROMPT,
) -> None:
    """Classify every not-yet-done snippet with the workhorse via the Message Batches API.

    One request per row instead of the gold/scale path's two, since no judge pass is
    needed. Results land only when the whole batch ends, so this suits an unattended
    run (decisions/009).

    Args:
        client: Authenticated Anthropic client.
        df: Frame with at least columns ``id`` and ``text``.
        done_ids: Ids that already have predictions and can be skipped.
        poll_interval: Seconds between status polls.
        preds_path: CSV the workhorse predictions are appended to.
        system_prompt: Prompt to classify under. Defaults to the live
            ``SYSTEM_PROMPT``; see :func:`run_workhorse`.
    """
    todo = df[~df["id"].isin(done_ids)].reset_index(drop=True)
    if todo.empty:
        return

    requests = [
        build_batch_request(
            str(row["id"]),
            row["text"],
            model=WORKHORSE_MODEL,
            system_prompt=system_prompt,
        )
        for _, row in todo.iterrows()
    ]
    print(
        f"Submitting a batch of {len(requests)} workhorse requests "
        f"({len(todo)} rows x 1 model)...",
        flush=True,
    )
    batch = client.messages.batches.create(requests=requests)
    print(
        f"Batch {batch.id} submitted; polling every {poll_interval:.0f}s...", flush=True
    )
    while True:
        batch = client.messages.batches.retrieve(batch.id)
        if batch.processing_status == "ended":
            break
        print(
            f"  status={batch.processing_status}  "
            f"processing={batch.request_counts.processing}",
            flush=True,
        )
        time.sleep(poll_interval)

    print("Batch ended; retrieving results...", flush=True)
    rows: list[dict] = []
    for result in client.messages.batches.results(batch.id):
        try:
            pred = parse_batch_result(result)
        except (BatchItemError, InvalidLabelError) as exc:
            # Leave the row todo rather than record a hole; the next pass picks it up.
            print(f"  [skip] id={result.custom_id}: {exc}", flush=True)
            continue
        rows.append(
            {
                "id": result.custom_id,
                "pred_category": pred["category"],
                "pred_operational_domain": pred["operational_domain"],
                "pred_region": pred["region"],
            }
        )

    if not rows:
        return
    write_header = not os.path.exists(preds_path)
    pd.DataFrame(rows)[CANDIDATE_COLUMNS].to_csv(
        preds_path, mode="a", header=write_header, index=False
    )


# ---------------------------------------------------------------------------
# Scoring: the named cluster, then the paired comparison.
# ---------------------------------------------------------------------------


def named_pull_ids(baseline: pd.DataFrame) -> list[str]:
    """The ids of the named cluster: answer-key ``global`` rows pulled to a region.

    Derived from the committed baseline rather than hardcoded. A pinned list would be a
    second source of truth for a fact the CSV already states, and it would silently
    stop describing the file the day either column moved. ADR-022 measured 17 of these
    at n=300; the report prints the count so a drift is visible rather than assumed.

    Args:
        baseline: The baseline predictions frame.

    Returns:
        Row ids, in file order, where the judge said ``global`` and the workhorse
        named a specific region.
    """
    pulled = baseline[
        (baseline["judge_region"] == GLOBAL) & (baseline["pred_region"] != GLOBAL)
    ]
    return [str(row_id) for row_id in pulled["id"]]


def cluster_delta(baseline: pd.DataFrame, candidate: pd.DataFrame) -> dict:
    """Account for the clause's effect on the named cluster and on its converse.

    Both directions, explicitly, because a clause that pushes rows toward ``global``
    cannot fix the pull without risking the over-call -- and reporting only the fixes
    is how a prompt change gets adopted on a number that nets out to zero. The n=300
    baseline already carried 10 over-called-``global`` rows before any clause existed.

    Args:
        baseline: Baseline predictions (workhorse + judge columns).
        candidate: Candidate predictions (workhorse columns only).

    Returns:
        Dict with the named-pull fix accounting, the over-call counts on both arms,
        which rows newly over-called ``global``, and the net region row change.
    """
    merged = baseline.merge(candidate, on="id", suffixes=("_base", "_cand"))
    named = merged[
        (merged["judge_region"] == GLOBAL) & (merged["pred_region_base"] != GLOBAL)
    ]
    fixed = named[named["pred_region_cand"] == GLOBAL]

    def _over(column: str) -> pd.DataFrame:
        return merged[(merged[column] == GLOBAL) & (merged["judge_region"] != GLOBAL)]

    over_base, over_cand = _over("pred_region_base"), _over("pred_region_cand")
    newly_over = over_cand[~over_cand["id"].isin(set(over_base["id"]))]

    # B EXACTLY AS THE DECISION RULE DEFINES IT: rows the baseline got RIGHT that the
    # candidate drags to `global`. "Newly over-called global" above is a different and
    # weaker quantity -- it also counts rows whose baseline answer was already wrong
    # (wrong-region -> global is not a regression, it was a miss either way). Reporting
    # only the weaker one would understate the cost the pre-registered rule is priced on.
    was_right = merged["pred_region_base"] == merged["judge_region"]
    broke_to_global = merged[
        was_right
        & (merged["pred_region_cand"] == GLOBAL)
        & (merged["judge_region"] != GLOBAL)
    ]
    broke_any = merged[
        was_right & (merged["pred_region_cand"] != merged["judge_region"])
    ]

    correct_base = int(was_right.sum())
    correct_cand = int((merged["pred_region_cand"] == merged["judge_region"]).sum())
    return {
        "n": len(merged),
        "named_pulls": len(named),
        "named_fixed": len(fixed),
        "named_fixed_ids": [str(i) for i in fixed["id"]],
        "named_unfixed_ids": [
            str(i) for i in named[named["pred_region_cand"] != GLOBAL]["id"]
        ],
        "over_global_baseline": len(over_base),
        "over_global_candidate": len(over_cand),
        "newly_over_global": len(newly_over),
        "newly_over_global_ids": [str(i) for i in newly_over["id"]],
        # The two quantities the decision rule is actually priced on.
        "F": len(fixed),
        "B": len(broke_to_global),
        "B_ids": [str(i) for i in broke_to_global["id"]],
        "regressions_any_label": len(broke_any),
        "regressions_any_label_ids": [str(i) for i in broke_any["id"]],
        "region_correct_baseline": correct_base,
        "region_correct_candidate": correct_cand,
        "region_net_rows": correct_cand - correct_base,
    }


def duplicate_snippet_ids(scale: pd.DataFrame) -> list[str]:
    """Ids whose snippet text is byte-identical to an earlier row's, whitespace aside.

    The scale set carries exact-duplicate snippets under different DVIDS ids: s022/s023,
    s024/s025, s078/s079/s080, s239/s240 -- nine rows in four groups. They matter for
    two reasons, and only one of them is statistical.

    - **McNemar assumes independent pairs.** Duplicated inputs are not independent
      observations, so leaving them in makes the significance threshold mildly
      anti-conservative -- the direction that flatters a positive result.
    - **s024/s025 are byte-identical and the answer key labels them differently**
      (``europe`` vs ``middle-east``). At most one can be right, so at least one row is
      unwinnable for any classifier, including a perfect one.

    The first occurrence is kept and the rest are dropped from the PAIRING only. Nothing
    is relabelled and no file is rewritten: the answer key is a shipped record and this
    experiment does not get to edit its own ruler.

    Args:
        scale: The scale set, with ``id`` and ``text``.

    Returns:
        Ids to exclude, sorted.
    """
    normalized = scale["text"].astype(str).str.strip()
    return sorted(
        str(row_id) for row_id in scale[normalized.duplicated(keep="first")]["id"]
    )


def answers_for(baseline: pd.DataFrame, judge_column: str) -> dict[str, str]:
    """Build ``group key -> answer-key label`` from an in-memory baseline frame.

    ``paired_compare.load_answer_key`` reads from a path, which cannot express "the
    committed key minus the duplicate rows". This builds the same mapping from a frame
    using ``paired_compare``'s own public ``derive_group_key``, so the key derivation
    stays shared even though the loading does not.

    Args:
        baseline: The (possibly deduplicated) baseline frame.
        judge_column: Which judge column supplies the labels.

    Returns:
        Group key to normalized label.
    """
    return {
        paired_compare.derive_group_key(record): str(record[judge_column])
        .strip()
        .lower()
        for record in baseline.to_dict("records")
    }


def axis_comparison(
    baseline: pd.DataFrame, candidate: pd.DataFrame, axis: str, judge_column: str
) -> tuple[paired_compare.PairingResult, paired_compare.CorrectnessLift]:
    """Run one axis's paired comparison through ``paired_compare``.

    The answer key and the baseline arm are the *same file*, read twice for different
    columns: ``judge_{axis}`` is the frozen ruler, ``pred_{axis}`` is the baseline arm's
    answer. Nothing about that is a special case for ``paired_compare`` -- it already
    takes an explicit ``--truth-column`` -- so this comparison runs through the repo's
    existing, tested pairing and McNemar code rather than a private reimplementation.

    Args:
        baseline: The (deduplicated) baseline predictions frame.
        candidate: The (deduplicated) candidate predictions frame.
        axis: ``region``, ``category``, or ``operational_domain``.
        judge_column: The answer-key column for this axis.

    Returns:
        The pairing result and the correctness summary.
    """
    answers = answers_for(baseline, judge_column)
    column = f"pred_{axis}"
    result = paired_compare.pair_observations(
        paired_compare.observations_from_frame(baseline, "baseline", column, answers),
        paired_compare.observations_from_frame(
            candidate,
            "candidate",
            column,
            answers,
        ),
    )
    return result, paired_compare.summarize_correctness(result.pairs)


# ---------------------------------------------------------------------------
# Report.
# ---------------------------------------------------------------------------


def optional_format(value: float | None, spec: str) -> str:
    """Format an optional number, keeping 'nothing to compare' distinct from zero.

    Local rather than imported from ``paired_compare``: that module's equivalents are
    private, and reaching across a module boundary for a private helper couples this
    report to another module's internals for two lines of formatting.

    Public (renamed from ``_optional``) because the higher-power re-run renders the
    same table -- the same reason ``scale_eval``'s ``accuracy_row`` / ``per_label`` /
    ``limitations_block`` were made public when a second eval began computing through
    them. A pure rename: no behavior change, no artifact regenerated.

    Args:
        value: The number, or ``None`` when there was nothing to compute it over.
        spec: Format spec applied when the value is present.

    Returns:
        The formatted number, or ``"n/a"``.
    """
    return "n/a" if value is None else format(value, spec)


def cluster_block(delta: dict) -> list[str]:
    """Format the named-cluster accounting.

    Public (renamed from ``_cluster_block``) so the higher-power re-run prints the
    F/B accounting in exactly this shape rather than a look-alike -- the two reports
    disagreeing about how B is counted is the one difference a reader would never
    catch. Pure rename; the frozen ``evals/region_clause_ab.txt`` is unaffected
    because nothing regenerates it.

    Args:
        delta: Output of :func:`cluster_delta`.

    Returns:
        Report lines.
    """
    fixed_rate = (
        f"{delta['named_fixed'] / delta['named_pulls']:.0%}"
        if delta["named_pulls"]
        else "n/a"
    )
    lines = [
        "",
        "-- The named `global` cluster ------------------------------",
        "The rows the clause was written for: answer-key `global` that the",
        "BASELINE pulled to a specific region (ADR-022 measured 17 at n=300).",
        "",
        f"Named pulls in the baseline     : {delta['named_pulls']}",
        f"  fixed by the clause           : {delta['named_fixed']}   ({fixed_rate})",
        f"  still pulled                  : {len(delta['named_unfixed_ids'])}",
        "",
        "-- The converse, which is how this clause could lose --------",
        "A clause that moves rows toward `global` buys its fixes with",
        "over-calls. Both directions or neither.",
        "",
        f"Over-called `global`, baseline  : {delta['over_global_baseline']}",
        f"Over-called `global`, candidate : {delta['over_global_candidate']}",
        f"  of which NEW                  : {delta['newly_over_global']}",
        "",
        "B, AS THE DECISION RULE DEFINES IT -- rows the baseline got RIGHT",
        "that the candidate drags to `global`. Distinct from `NEW` above,",
        "which also counts rows that were already wrong (wrong-region ->",
        "`global` costs nothing; it was a miss either way).",
        "",
        f"F (named pulls fixed)           : {delta['F']}",
        f"B (correct rows dragged global) : {delta['B']}",
        f"Regressions on any label        : {delta['regressions_any_label']}",
        "",
        "-- Net, on region rows -------------------------------------",
        f"Region correct, baseline        : {delta['region_correct_baseline']}"
        f"/{delta['n']}",
        f"Region correct, candidate       : {delta['region_correct_candidate']}"
        f"/{delta['n']}",
        f"Net row change                  : {delta['region_net_rows']:+d}",
    ]
    if delta["named_fixed_ids"]:
        lines.append("")
        lines.append("Fixed ids       : " + ", ".join(delta["named_fixed_ids"]))
    if delta["named_unfixed_ids"]:
        lines.append("Still pulled    : " + ", ".join(delta["named_unfixed_ids"]))
    if delta["newly_over_global_ids"]:
        lines.append("Newly over-called: " + ", ".join(delta["newly_over_global_ids"]))
    if delta["B_ids"]:
        lines.append("B ids           : " + ", ".join(delta["B_ids"]))
    return lines


def build_report(
    baseline: pd.DataFrame,
    candidate: pd.DataFrame,
    comparisons: list[
        tuple[str, paired_compare.PairingResult, paired_compare.CorrectnessLift]
    ],
    baseline_recorded: dict[str, str],
    candidate_recorded: dict[str, str],
    excluded: list[str],
    key_digest: str,
) -> str:
    """Assemble the A/B report.

    Args:
        baseline: Baseline predictions frame (already deduplicated).
        candidate: Candidate predictions frame (already deduplicated).
        comparisons: ``(axis, pairing result, correctness lift)`` per axis.
        baseline_recorded: The baseline sidecar's ``recorded`` block.
        candidate_recorded: The candidate sidecar's ``recorded`` block.
        excluded: Ids dropped from the pairing as exact-duplicate snippets.
        key_digest: Content fingerprint of the answer key actually used.

    Returns:
        The report text.
    """
    delta = cluster_delta(baseline, candidate)
    lines = [
        "=" * 62,
        "`global`-BOUNDARY CLAUSE A/B -- workhorse prompt",
        "=" * 62,
        "",
        f"Snippets scored   : {delta['n']}   ({SCALE_SET_PATH})",
        f"  excluded as exact duplicates: {len(excluded)}"
        + (f"  ({', '.join(excluded)})" if excluded else ""),
        f"Workhorse         : {candidate_recorded.get('workhorse_model')}",
        f"Answer key        : {candidate_recorded.get('judge_model')} judge labels,",
        f"                    FROZEN, reused from {BASELINE_PREDS_PATH}",
        f"Answer-key digest : {key_digest}   (recomputable from the committed CSV)",
        "",
        "The judge was NOT re-run. gold_eval.run_predictions classifies each row",
        "with the workhorse and the judge independently, from the snippet text",
        "alone -- neither sees the other's answer -- so a judge label cannot",
        "depend on the workhorse's PREDICTION. Holding it fixed is what makes",
        "this a paired comparison instead of two runs graded by two rulers.",
        "(A judge label IS prompt-dependent -- classify() defaults both models",
        "to SYSTEM_PROMPT -- which is precisely why it must not be re-run here.)",
        "",
        "Exact-duplicate snippets are dropped from the PAIRING, not relabelled:",
        "they violate McNemar's independence assumption, and one duplicate pair",
        "(s024/s025) carries two DIFFERENT answer-key labels on identical text,",
        "so at least one of them is unwinnable for any classifier.",
        "",
        f"Baseline prompt   : {baseline_recorded.get('prompt_sha256')}",
        f"Candidate prompt  : {candidate_recorded.get('prompt_sha256')}",
        "",
        "-- Paired comparison, per axis -----------------------------",
        "Region is the target. Category and domain are GUARDRAILS: ADR-020's",
        "critic fixed its named region cluster and did significant damage to",
        "domain (p=0.016) in the same run. Significant harm on either kills",
        "this clause regardless of what region does.",
        "",
        "McNemar p below is computed over ALL discordant pairs on the axis,",
        "not only over F and B -- a row the clause flips between two specific",
        "regions counts too. F and B are the named-cluster accounting below.",
        "",
        f"{'axis':<20}{'base':>8}{'cand':>8}{'lift':>9}"
        f"{'c/b/tie':>13}{'McNemar p':>12}",
    ]
    for axis, _result, lift in comparisons:
        base = optional_format(lift.baseline_pass_rate, ".1%")
        cand = optional_format(lift.candidate_pass_rate, ".1%")
        shift = optional_format(lift.lift, "+.1%")
        wins = f"{lift.candidate_wins}/{lift.baseline_wins}/{lift.ties}"
        lines.append(
            f"{axis:<20}{base:>8}{cand:>8}{shift:>9}{wins:>13}{lift.p_value:>12.4f}"
        )

    lines += cluster_block(delta)
    lines += [
        "",
        "-- Harness health ------------------------------------------",
        "A lift computed over a harness that dropped rows is not a finding.",
        "",
    ]
    for axis, result, lift in comparisons:
        counts = paired_compare.diagnostic_counts(result.diagnostics)
        summary = ", ".join(f"{k}={v}" for k, v in counts.items() if v)
        lines.append(
            f"  {axis:<20} groups={result.total_groups}  pairs={lift.total_pairs}  "
            f"eligible={lift.eligible_pairs}"
        )
        lines.append(
            f"  {'':<20} {summary or 'clean -- every group paired and scored'}"
        )
    lines += [
        "",
        "-- How to read this ----------------------------------------",
        "Accuracy here is agreement with the JUDGE, not with a human. ADR-022's",
        "caveat carries over verbatim: the judge's measured disagreement with",
        "humans on region was 0/54, and 0/54 is itself a wide interval, so read",
        "these numbers alongside the human-graded gold figures, never instead of",
        "them. The gold arm is the human-graded half of this experiment.",
        "=" * 62,
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entry points.
# ---------------------------------------------------------------------------


def run(batch: bool = False) -> None:
    """Run the candidate workhorse pass over the scale set, then record provenance.

    The only function here that spends API budget: 1 call per not-yet-done snippet.

    Args:
        batch: Submit via the Message Batches API instead of N synchronous calls.

    Raises:
        ValueError: If resuming would blend two different classifiers.
    """
    os.makedirs("evals", exist_ok=True)
    scale = scale_eval.load_scale_set(SCALE_SET_PATH)
    print(f"Loaded {len(scale)} snippets from {SCALE_SET_PATH}\n")

    done_ids = (
        set(pd.read_csv(CANDIDATE_PREDS_PATH)["id"])
        if os.path.exists(CANDIDATE_PREDS_PATH)
        else set()
    )
    if done_ids:
        print(f"Resuming: {len(done_ids)} already predicted.\n")

    # BEFORE the "nothing to do" early return, not after. An existing complete CSV
    # produced by a different prompt is exactly the case that most needs catching, and
    # returning early would have skipped the check and left a stale arm in place for
    # report() to compare -- where assert_arms_differ would pass it, because it only
    # proves the two arms differ from EACH OTHER, not that either is the live prompt.
    live = provenance.fingerprint(SYSTEM_PROMPT, WORKHORSE_MODEL, JUDGE_MODEL)
    assert_resume_is_honest(done_ids, live)

    remaining = set(scale["id"]) - done_ids
    if not remaining:
        print("All predictions already present -- skipping API calls.\n")
        return

    client = make_client()
    # Passed explicitly rather than relying on the default: a default argument binds at
    # definition time, so a caller (or a test) that repoints CANDIDATE_PREDS_PATH would
    # otherwise be silently ignored and write to the module-level path anyway.
    if batch:
        run_workhorse_batch(client, scale, done_ids, preds_path=CANDIDATE_PREDS_PATH)
    else:
        run_workhorse(client, scale, done_ids, preds_path=CANDIDATE_PREDS_PATH)

    # Written only on the path that made API calls, so a report-only rerun can never
    # assert that today's prompt produced yesterday's rows.
    provenance.write(live, CANDIDATE_PREDS_PATH, path=CANDIDATE_PROVENANCE_PATH)
    print(f"Recorded run provenance to {CANDIDATE_PROVENANCE_PATH}\n")

    # The sidecar is written even on a partial pass, because the resume guard needs it
    # to exist before the NEXT append can be checked. So say plainly that it describes
    # an incomplete arm; `--report` refuses one outright (assert_candidate_is_complete).
    landed = set(pd.read_csv(CANDIDATE_PREDS_PATH)["id"])
    still_missing = set(scale["id"]) - landed
    if still_missing:
        print(
            f"PARTIAL RUN -- {len(still_missing)} of {len(scale)} rows did not land "
            f"(e.g. {sorted(str(i) for i in still_missing)[:5]}).\n"
            f"{CANDIDATE_PROVENANCE_PATH} now describes an INCOMPLETE arm. Re-run "
            "`--run` to finish it; `--report` will refuse until it is complete.\n",
            flush=True,
        )


def report() -> str:
    """Score the two committed arms and write the report.

    Entirely offline: no client, no key, no API call.

    Returns:
        The report text.

    Raises:
        FileNotFoundError: If either sidecar is missing -- an unknown pairing must not
            read as a verified one.
        ValueError: If a guard finds the comparison would not mean what it claims.
    """
    os.makedirs("evals", exist_ok=True)
    # dtype=str, keep_default_na=False (via paired_compare.read_predictions): with a
    # bare read_csv a blank cell arrives as NaN, so the answer-key blank check compared
    # the string "nan" against "" and could never fire on the production path.
    baseline = paired_compare.read_predictions(BASELINE_PREDS_PATH)
    candidate = paired_compare.read_predictions(CANDIDATE_PREDS_PATH)
    scale = scale_eval.load_scale_set(SCALE_SET_PATH)

    assert_answer_key_is_complete(baseline, scale)
    assert_candidate_is_complete(baseline, candidate)

    baseline_recorded = provenance.load(BASELINE_PROVENANCE_PATH)["recorded"]
    candidate_recorded = provenance.load(CANDIDATE_PROVENANCE_PATH)["recorded"]
    assert_arms_differ(baseline_recorded, candidate_recorded)
    assert_candidate_matches_the_live_prompt(candidate_recorded)

    # Exact-duplicate snippets leave the PAIRING (not the files): they break McNemar's
    # independence assumption, and one duplicate pair is labelled inconsistently by the
    # answer key itself. See duplicate_snippet_ids.
    excluded = duplicate_snippet_ids(scale)
    baseline = baseline[~baseline["id"].astype(str).isin(excluded)]
    candidate = candidate[~candidate["id"].astype(str).isin(excluded)]

    comparisons = [
        (axis, *axis_comparison(baseline, candidate, axis, col)) for axis, col in AXES
    ]
    text = (
        build_report(
            baseline,
            candidate,
            comparisons,
            baseline_recorded,
            candidate_recorded,
            excluded,
            judge_digest(baseline),
        )
        + "\n"
    )
    atomic_write_text(REPORT_PATH, text)
    return text


def main() -> None:
    """CLI entrypoint: ``--run`` spends API budget, ``--report`` never does."""
    parser = argparse.ArgumentParser(
        description="A/B the `global`-boundary prompt clause against the n=300 ruler."
    )
    parser.add_argument(
        "--run",
        action="store_true",
        help="LIVE: classify the scale set with the workhorse under the current prompt "
        "(~N calls; the judge is NOT re-run).",
    )
    parser.add_argument(
        "--batch",
        action="store_true",
        help="with --run, submit via the Message Batches API (~50%% cheaper, "
        "non-interactive).",
    )
    parser.add_argument(
        "--report",
        action="store_true",
        help="OFFLINE: score the two committed arms and write the report.",
    )
    args = parser.parse_args()

    if not args.run and not args.report:
        parser.error("nothing to do: pass --run and/or --report")
    if args.batch and not args.run:
        parser.error("--batch only applies to --run")
    if args.run:
        run(batch=args.batch)
    if args.report:
        print(report())


if __name__ == "__main__":
    main()
